### ISSUE TITLE
Server crash when trying to nullify water

### ISSUE THREAD

**Issue by thejims** [Bartz24/UsefulNullifiers#7]
Attempted to pick up/nullify a block of water, server AND client crashed.

Version:        UCHIJAAAA       usefulnullifiers{1.3.3} [Useful Nullifiers] (useful-nullifiers.jar)
Forge:        FML: MCP 9.38 Powered by Forge 13.20.0.2226 145 mods loaded, 145 mods active

Player crash: http://pastebin.com/XtfirTZH
Server crash: http://pastebin.com/Zju62KFi

Snippet of server crash:
Description: Ticking player

java.lang.NoSuchMethodError: mcjty.lib.tools.ItemStackList.get(I)Lnet/minecraft/item/ItemStack;
        at com.bartz24.usefulnullifiers.inventory.FluidVoidInventory.func_70301_a(FluidVoidInventory.java:50)
        at net.minecraft.inventory.Slot.func_75211_c(Slot.java:60)
        at net.minecraft.inventory.Container.func_75142_b(Container.java:75)
        at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:280)
        at net.minecraft.world.World.func_72866_a(World.java:1961)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
        at net.minecraft.world.World.func_72870_g(World.java:1931)
        at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:650)
        at net.minecraft.world.World.func_72939_s(World.java:1723)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
        at java.lang.Thread.run(Thread.java:745)

**Comment by Bartz24** [comment]
Fixed for next version
